/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package attendencesystem;

import java.awt.event.KeyEvent;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.StringTokenizer;

/**
 *
 * @author SHIVAM AGRAWAL
 */
public class Edit extends java.awt.Frame {

    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
        setLocation(250,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label6 = new java.awt.Label();
        fnm = new java.awt.TextField();
        lnm = new java.awt.TextField();
        dobd = new java.awt.TextField();
        dobm = new java.awt.TextField();
        doby = new java.awt.TextField();
        city = new java.awt.TextField();
        button3 = new java.awt.Button();
        label5 = new java.awt.Label();
        label7 = new java.awt.Label();
        rn = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        label = new java.awt.Label();

        setBackground(new java.awt.Color(204, 255, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 153, 153));
        label1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 0));
        label1.setText("Edit Student Details");

        label2.setBackground(new java.awt.Color(189, 220, 253));
        label2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("First Name");

        label3.setBackground(new java.awt.Color(189, 220, 253));
        label3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label3.setText("Last Name");

        label4.setBackground(new java.awt.Color(189, 220, 253));
        label4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label4.setText("Date of Birth");

        label6.setBackground(new java.awt.Color(189, 220, 253));
        label6.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        label6.setText("City");

        fnm.setBackground(new java.awt.Color(189, 220, 253));
        fnm.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        lnm.setBackground(new java.awt.Color(189, 220, 253));
        lnm.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        dobd.setBackground(new java.awt.Color(189, 220, 253));
        dobd.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        dobm.setBackground(new java.awt.Color(189, 220, 253));
        dobm.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        doby.setBackground(new java.awt.Color(189, 220, 253));
        doby.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        city.setBackground(new java.awt.Color(189, 220, 253));
        city.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N

        button3.setBackground(new java.awt.Color(0, 204, 204));
        button3.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        button3.setLabel("Exit");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        label5.setBackground(new java.awt.Color(0, 102, 102));

        label7.setBackground(new java.awt.Color(153, 255, 204));
        label7.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        label7.setText("Enter Roll No.");

        rn.setBackground(new java.awt.Color(153, 255, 204));
        rn.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        rn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                rnKeyPressed(evt);
            }
        });

        button1.setBackground(new java.awt.Color(153, 255, 204));
        button1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        button1.setLabel("Q");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 204, 204));
        button2.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N
        button2.setLabel("Save");
        button2.setName(""); // NOI18N
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("DialogInput", 1, 20)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dobd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dobm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(doby, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fnm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(rn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(doby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        setVisible(false);
    }//GEN-LAST:event_exitForm

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_button3ActionPerformed

    private void rnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rnKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        search();
    }//GEN-LAST:event_rnKeyPressed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        search();
    }//GEN-LAST:event_button1ActionPerformed

    String pnm;
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        String fn=fnm.getText();
        String ln=lnm.getText();
        int dd=Integer.parseInt(dobd.getText());
        int dm=Integer.parseInt(dobm.getText());
        int dy=Integer.parseInt(doby.getText());
        String citi=city.getText();
        int roll=Integer.parseInt(rn.getText());
         String fd=fn+" "+ln+"@"+roll+"@"+dd+"-"+dm+"-"+dy+"@"+citi;
        byte arr[]=fd.getBytes();

        try {

            FileOutputStream fout;
            FileInputStream fin;
            fin=new FileInputStream("Student_List.txt");
            int a;
            String data2="";
            while((a=fin.read())!=-1)
                data2=data2+(char)a;
            StringBuffer data3=new StringBuffer(data2);
            int index=data2.indexOf(roll+"");
            index+=4;
            int lindex=data2.indexOf("@",index);
            //lindex--;
            data3.replace(index,lindex,(fn+" "+ln));
                    
            fout=new FileOutputStream("Student_List.txt");
            fout.write(data3.toString().getBytes());

            fout=new FileOutputStream(roll+".txt");
            fout.write(arr);
            label.setBackground(java.awt.Color.GREEN);
            label.setText("Student details changed Successfully");
            fout.close();
        } catch (Exception ex) {label.setText("Student details couldn't be changed");
            label.setBackground(java.awt.Color.RED);}

    }//GEN-LAST:event_button2ActionPerformed

    int rol;
    String naam;
    String nl=System.getProperty("line.separator").toString();
     void search()
    {
        int a=Integer.parseInt(rn.getText());
        rol=a;
        String aaa="";
        
        try{
            FileInputStream fin=new FileInputStream(a+".txt");
            int aa;
            while((aa=fin.read())!=-1)
            {
                aaa=aaa+(char)aa;
            }
        StringTokenizer st=new StringTokenizer(aaa,"@");
        naam=st.nextToken();
        StringTokenizer st1=new StringTokenizer(naam," ");
        fnm.setText(st1.nextToken());
        lnm.setText(st1.nextToken());
        pnm=fnm+" "+lnm;
        st.nextToken();
        StringTokenizer st2=new StringTokenizer(st.nextToken(),"-");
        dobd.setText(st2.nextToken());
        dobm.setText(st2.nextToken());
        doby.setText(st2.nextToken());
        city.setText(st.nextToken());
        }catch(Exception e){System.out.println(e);}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.TextField city;
    private java.awt.TextField dobd;
    private java.awt.TextField dobm;
    private java.awt.TextField doby;
    private java.awt.TextField fnm;
    private java.awt.Label label;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.TextField lnm;
    private java.awt.TextField rn;
    // End of variables declaration//GEN-END:variables
}
